version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.8.1
    - 1.9.1
  - dependency-name: bundler
    versions:
    - 2.2.6
    - 2.2.7
  - dependency-name: i18n
    versions:
    - 1.8.7
