AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'Gemfile'
    - 'turkish_cities.gemspec'
Layout/LineLength:
  Max: 100
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Description: 'Prefer `transform_keys` over `each_with_object` and `map`.'
  Enabled: true
Style/HashTransformValues:
  Description: 'Prefer `transform_values` over `each_with_object` and `map`.'
  Enabled: true
